# -*- coding: utf-8 -*-
"""AI_construction_rag_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gkreNyvLxK_FebmOaOUY9aYszSlI5KE
"""

!pip install sentence-transformers faiss-cpu openai

import os

os.makedirs("data", exist_ok=True)

print("Folder created:", os.listdir())

documents = []

for file in os.listdir("data"):
    with open(f"data/{file}", "r", encoding="utf-8") as f:
        documents.append(f.read())

print("Loaded docs:", len(documents))

def chunk_text(text, size=500):
    paras = text.split("\n")
    chunks = []
    temp = ""

    for p in paras:
        if len(temp) + len(p) < size:
            temp += " " + p
        else:
            chunks.append(temp)
            temp = p

    chunks.append(temp)
    return chunks


all_text = "\n".join(documents)

chunks = chunk_text(all_text)

print("Chunks:", len(chunks))

embed_model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = embed_model.encode(chunks)

dim = embeddings.shape[1]

index = faiss.IndexFlatIP(dim)   # cosine style similarity
index.add(np.array(embeddings))

print("Vector DB ready")

def retrieve(query, k=4):
    q = embed_model.encode([query])
    D, I = index.search(np.array(q), k)
    return [chunks[i] for i in I[0]]

from openai import OpenAI

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key="put your api key"
)

import time

def generate_answer(ctx, q):

    context = "\n\n".join(ctx)

    prompt = f"""
You are an AI assistant for a construction marketplace.

STRICT RULES:
- Answer ONLY using retrieved context
- If partially available → summarize best possible
- If missing → say "Information not available in documents"
- Be concise
- Explain reasoning from context

Context:
{context}

Question:
{q}

Answer:
"""

    models = [
        "deepseek/deepseek-chat",              # primary
        "meta-llama/llama-3-8b-instruct",      # fallback
        "google/gemma-2-9b-it"                 # second fallback
    ]

    for model in models:
        try:
            res = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2
            )
            return res.choices[0].message.content

        except Exception as e:
            print(f"Model {model} failed, trying next...")
            time.sleep(2)

    return "LLM temporarily unavailable. Please try again later."

ask("How are construction delays managed?")

